/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSplatRouteImport } from './routes/_app.$'
import { Route as AppBorcAlacakRouteImport } from './routes/_app.borc-alacak'
import { Route as AppGiderRouteImport } from './routes/_app.gider'
import { Route as AppKasaHareketleriRouteImport } from './routes/_app.kasa-hareketleri'
import { Route as AppKdvKategorisiRouteImport } from './routes/_app.kdv-kategorisi'
import { Route as AppKisilerRouteImport } from './routes/_app.kisiler'
import { Route as AppLoginRouteImport } from './routes/_app.login'
import { Route as AppLogoutRouteImport } from './routes/_app.logout'
import { Route as AppNobetHareketleriRouteImport } from './routes/_app.nobet-hareketleri'
import { Route as AppSatisRouteImport } from './routes/_app.satis'
import { Route as AppSatisStokHareketleriRouteImport } from './routes/_app.satis-stok-hareketleri'
import { Route as AppStokGirisiRouteImport } from './routes/_app.stok-girisi'
import { Route as AppUreticiRouteImport } from './routes/_app.uretici'
import { Route as AppUreticiOdemeleriRouteImport } from './routes/_app.uretici-odemeleri'
import { Route as AppUrunRouteImport } from './routes/_app.urun'
import { Route as AppUrunFiyatRouteImport } from './routes/_app.urun-fiyat'
import { Route as AppUrunFiyatHesapRouteImport } from './routes/_app.urun-fiyat-hesap'
import { Route as AppVirmanRouteImport } from './routes/_app.virman'
import { Route as AppAccountActivateRouteImport } from './routes/_app.account.activate'
import { Route as AppAccountPasswordRouteImport } from './routes/_app.account.password'
import { Route as AppAccountSettingsRouteImport } from './routes/_app.account.settings'
import { Route as AppAdminAuditsRouteImport } from './routes/_app.admin.audits'
import { Route as AppAdminHealthRouteImport } from './routes/_app.admin.health'
import { Route as AppAdminOperationsRouteImport } from './routes/_app.admin.operations'
import { Route as AppAdminUserManagementRouteImport } from './routes/_app.admin.user-management'
import { Route as AppBorcAlacakIdRouteImport } from './routes/_app.borc-alacak_.$id'
import { Route as AppBorcAlacakNewRouteImport } from './routes/_app.borc-alacak_.new'
import { Route as AppGiderIdRouteImport } from './routes/_app.gider_.$id'
import { Route as AppGiderNewRouteImport } from './routes/_app.gider_.new'
import { Route as AppKasaHareketleriIdRouteImport } from './routes/_app.kasa-hareketleri_.$id'
import { Route as AppKasaHareketleriNewRouteImport } from './routes/_app.kasa-hareketleri_.new'
import { Route as AppKdvKategorisiIdRouteImport } from './routes/_app.kdv-kategorisi_.$id'
import { Route as AppKdvKategorisiNewRouteImport } from './routes/_app.kdv-kategorisi_.new'
import { Route as AppKisilerIdRouteImport } from './routes/_app.kisiler_.$id'
import { Route as AppKisilerNewRouteImport } from './routes/_app.kisiler_.new'
import { Route as AppNobetHareketleriIdRouteImport } from './routes/_app.nobet-hareketleri_.$id'
import { Route as AppNobetHareketleriNewRouteImport } from './routes/_app.nobet-hareketleri_.new'
import { Route as AppReportsAylikSatislarRouteImport } from './routes/_app.reports.aylikSatislar'
import { Route as AppReportsAylikSatislarMaliRouteImport } from './routes/_app.reports.aylikSatislarMali'
import { Route as AppReportsCiroRouteImport } from './routes/_app.reports.ciro'
import { Route as AppReportsOrtakFaturalarRouteImport } from './routes/_app.reports.ortakFaturalar'
import { Route as AppReportsStockRouteImport } from './routes/_app.reports.stock'
import { Route as AppReportsTukenmeRouteImport } from './routes/_app.reports.tukenme'
import { Route as AppSatisStokHareketleriIdRouteImport } from './routes/_app.satis-stok-hareketleri_.$id'
import { Route as AppSatisStokHareketleriNewRouteImport } from './routes/_app.satis-stok-hareketleri_.new'
import { Route as AppSatisIdRouteImport } from './routes/_app.satis_.$id'
import { Route as AppSatisNewRouteImport } from './routes/_app.satis_.new'
import { Route as AppStokGirisiIdRouteImport } from './routes/_app.stok-girisi_.$id'
import { Route as AppStokGirisiNewRouteImport } from './routes/_app.stok-girisi_.new'
import { Route as AppUreticiOdemeleriIdRouteImport } from './routes/_app.uretici-odemeleri_.$id'
import { Route as AppUreticiOdemeleriNewRouteImport } from './routes/_app.uretici-odemeleri_.new'
import { Route as AppUreticiIdRouteImport } from './routes/_app.uretici_.$id'
import { Route as AppUreticiNewRouteImport } from './routes/_app.uretici_.new'
import { Route as AppUrunFiyatHesapIdRouteImport } from './routes/_app.urun-fiyat-hesap_.$id'
import { Route as AppUrunFiyatHesapNewRouteImport } from './routes/_app.urun-fiyat-hesap_.new'
import { Route as AppUrunFiyatIdRouteImport } from './routes/_app.urun-fiyat_.$id'
import { Route as AppUrunFiyatNewRouteImport } from './routes/_app.urun-fiyat_.new'
import { Route as AppUrunIdRouteImport } from './routes/_app.urun_.$id'
import { Route as AppUrunNewRouteImport } from './routes/_app.urun_.new'
import { Route as AppVirmanIdRouteImport } from './routes/_app.virman_.$id'
import { Route as AppVirmanNewRouteImport } from './routes/_app.virman_.new'
import { Route as AppAccountResetFinishRouteImport } from './routes/_app.account.reset.finish'
import { Route as AppAccountResetRequestRouteImport } from './routes/_app.account.reset.request'
import { Route as AppAdminUserManagementLoginRouteImport } from './routes/_app.admin.user-management_.$login'
import { Route as AppAdminUserManagementNewRouteImport } from './routes/_app.admin.user-management_.new'
import { Route as AppBorcAlacakIdDeleteRouteImport } from './routes/_app.borc-alacak_.$id_.delete'
import { Route as AppBorcAlacakIdEditRouteImport } from './routes/_app.borc-alacak_.$id_.edit'
import { Route as AppGiderIdDeleteRouteImport } from './routes/_app.gider_.$id_.delete'
import { Route as AppGiderIdEditRouteImport } from './routes/_app.gider_.$id_.edit'
import { Route as AppKasaHareketleriIdDeleteRouteImport } from './routes/_app.kasa-hareketleri_.$id_.delete'
import { Route as AppKasaHareketleriIdEditRouteImport } from './routes/_app.kasa-hareketleri_.$id_.edit'
import { Route as AppKdvKategorisiIdDeleteRouteImport } from './routes/_app.kdv-kategorisi_.$id_.delete'
import { Route as AppKdvKategorisiIdEditRouteImport } from './routes/_app.kdv-kategorisi_.$id_.edit'
import { Route as AppKisilerIdDeleteRouteImport } from './routes/_app.kisiler_.$id_.delete'
import { Route as AppKisilerIdEditRouteImport } from './routes/_app.kisiler_.$id_.edit'
import { Route as AppNobetHareketleriIdDeleteRouteImport } from './routes/_app.nobet-hareketleri_.$id_.delete'
import { Route as AppNobetHareketleriIdEditRouteImport } from './routes/_app.nobet-hareketleri_.$id_.edit'
import { Route as AppReportsCiroIdRouteImport } from './routes/_app.reports.ciro_.$id'
import { Route as AppReportsOrtakFaturalarIdRouteImport } from './routes/_app.reports.ortakFaturalar_.$id'
import { Route as AppSatisStokHareketleriIdDeleteRouteImport } from './routes/_app.satis-stok-hareketleri_.$id_.delete'
import { Route as AppSatisStokHareketleriIdEditRouteImport } from './routes/_app.satis-stok-hareketleri_.$id_.edit'
import { Route as AppSatisIdDeleteRouteImport } from './routes/_app.satis_.$id_.delete'
import { Route as AppSatisIdEditRouteImport } from './routes/_app.satis_.$id_.edit'
import { Route as AppStokGirisiIdDeleteRouteImport } from './routes/_app.stok-girisi_.$id_.delete'
import { Route as AppStokGirisiIdEditRouteImport } from './routes/_app.stok-girisi_.$id_.edit'
import { Route as AppUreticiOdemeleriIdDeleteRouteImport } from './routes/_app.uretici-odemeleri_.$id_.delete'
import { Route as AppUreticiOdemeleriIdEditRouteImport } from './routes/_app.uretici-odemeleri_.$id_.edit'
import { Route as AppUreticiIdDeleteRouteImport } from './routes/_app.uretici_.$id_.delete'
import { Route as AppUreticiIdEditRouteImport } from './routes/_app.uretici_.$id_.edit'
import { Route as AppUrunFiyatHesapIdDeleteRouteImport } from './routes/_app.urun-fiyat-hesap_.$id_.delete'
import { Route as AppUrunFiyatHesapIdEditRouteImport } from './routes/_app.urun-fiyat-hesap_.$id_.edit'
import { Route as AppUrunFiyatIdDeleteRouteImport } from './routes/_app.urun-fiyat_.$id_.delete'
import { Route as AppUrunFiyatIdEditRouteImport } from './routes/_app.urun-fiyat_.$id_.edit'
import { Route as AppUrunIdDeleteRouteImport } from './routes/_app.urun_.$id_.delete'
import { Route as AppUrunIdEditRouteImport } from './routes/_app.urun_.$id_.edit'
import { Route as AppVirmanIdDeleteRouteImport } from './routes/_app.virman_.$id_.delete'
import { Route as AppVirmanIdEditRouteImport } from './routes/_app.virman_.$id_.edit'
import { Route as AppAdminUserManagementLoginDeleteRouteImport } from './routes/_app.admin.user-management_.$login_.delete'
import { Route as AppAdminUserManagementLoginEditRouteImport } from './routes/_app.admin.user-management_.$login_.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppBorcAlacakRoute = AppBorcAlacakRouteImport.update({
  id: '/borc-alacak',
  path: '/borc-alacak',
  getParentRoute: () => AppRoute,
} as any)
const AppGiderRoute = AppGiderRouteImport.update({
  id: '/gider',
  path: '/gider',
  getParentRoute: () => AppRoute,
} as any)
const AppKasaHareketleriRoute = AppKasaHareketleriRouteImport.update({
  id: '/kasa-hareketleri',
  path: '/kasa-hareketleri',
  getParentRoute: () => AppRoute,
} as any)
const AppKdvKategorisiRoute = AppKdvKategorisiRouteImport.update({
  id: '/kdv-kategorisi',
  path: '/kdv-kategorisi',
  getParentRoute: () => AppRoute,
} as any)
const AppKisilerRoute = AppKisilerRouteImport.update({
  id: '/kisiler',
  path: '/kisiler',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppLogoutRoute = AppLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AppRoute,
} as any)
const AppNobetHareketleriRoute = AppNobetHareketleriRouteImport.update({
  id: '/nobet-hareketleri',
  path: '/nobet-hareketleri',
  getParentRoute: () => AppRoute,
} as any)
const AppSatisRoute = AppSatisRouteImport.update({
  id: '/satis',
  path: '/satis',
  getParentRoute: () => AppRoute,
} as any)
const AppSatisStokHareketleriRoute = AppSatisStokHareketleriRouteImport.update({
  id: '/satis-stok-hareketleri',
  path: '/satis-stok-hareketleri',
  getParentRoute: () => AppRoute,
} as any)
const AppStokGirisiRoute = AppStokGirisiRouteImport.update({
  id: '/stok-girisi',
  path: '/stok-girisi',
  getParentRoute: () => AppRoute,
} as any)
const AppUreticiRoute = AppUreticiRouteImport.update({
  id: '/uretici',
  path: '/uretici',
  getParentRoute: () => AppRoute,
} as any)
const AppUreticiOdemeleriRoute = AppUreticiOdemeleriRouteImport.update({
  id: '/uretici-odemeleri',
  path: '/uretici-odemeleri',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunRoute = AppUrunRouteImport.update({
  id: '/urun',
  path: '/urun',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunFiyatRoute = AppUrunFiyatRouteImport.update({
  id: '/urun-fiyat',
  path: '/urun-fiyat',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunFiyatHesapRoute = AppUrunFiyatHesapRouteImport.update({
  id: '/urun-fiyat-hesap',
  path: '/urun-fiyat-hesap',
  getParentRoute: () => AppRoute,
} as any)
const AppVirmanRoute = AppVirmanRouteImport.update({
  id: '/virman',
  path: '/virman',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountActivateRoute = AppAccountActivateRouteImport.update({
  id: '/account/activate',
  path: '/account/activate',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountPasswordRoute = AppAccountPasswordRouteImport.update({
  id: '/account/password',
  path: '/account/password',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountSettingsRoute = AppAccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditsRoute = AppAdminAuditsRouteImport.update({
  id: '/admin/audits',
  path: '/admin/audits',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminHealthRoute = AppAdminHealthRouteImport.update({
  id: '/admin/health',
  path: '/admin/health',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOperationsRoute = AppAdminOperationsRouteImport.update({
  id: '/admin/operations',
  path: '/admin/operations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUserManagementRoute = AppAdminUserManagementRouteImport.update({
  id: '/admin/user-management',
  path: '/admin/user-management',
  getParentRoute: () => AppRoute,
} as any)
const AppBorcAlacakIdRoute = AppBorcAlacakIdRouteImport.update({
  id: '/borc-alacak_/$id',
  path: '/borc-alacak/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBorcAlacakNewRoute = AppBorcAlacakNewRouteImport.update({
  id: '/borc-alacak_/new',
  path: '/borc-alacak/new',
  getParentRoute: () => AppRoute,
} as any)
const AppGiderIdRoute = AppGiderIdRouteImport.update({
  id: '/gider_/$id',
  path: '/gider/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGiderNewRoute = AppGiderNewRouteImport.update({
  id: '/gider_/new',
  path: '/gider/new',
  getParentRoute: () => AppRoute,
} as any)
const AppKasaHareketleriIdRoute = AppKasaHareketleriIdRouteImport.update({
  id: '/kasa-hareketleri_/$id',
  path: '/kasa-hareketleri/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppKasaHareketleriNewRoute = AppKasaHareketleriNewRouteImport.update({
  id: '/kasa-hareketleri_/new',
  path: '/kasa-hareketleri/new',
  getParentRoute: () => AppRoute,
} as any)
const AppKdvKategorisiIdRoute = AppKdvKategorisiIdRouteImport.update({
  id: '/kdv-kategorisi_/$id',
  path: '/kdv-kategorisi/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppKdvKategorisiNewRoute = AppKdvKategorisiNewRouteImport.update({
  id: '/kdv-kategorisi_/new',
  path: '/kdv-kategorisi/new',
  getParentRoute: () => AppRoute,
} as any)
const AppKisilerIdRoute = AppKisilerIdRouteImport.update({
  id: '/kisiler_/$id',
  path: '/kisiler/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppKisilerNewRoute = AppKisilerNewRouteImport.update({
  id: '/kisiler_/new',
  path: '/kisiler/new',
  getParentRoute: () => AppRoute,
} as any)
const AppNobetHareketleriIdRoute = AppNobetHareketleriIdRouteImport.update({
  id: '/nobet-hareketleri_/$id',
  path: '/nobet-hareketleri/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNobetHareketleriNewRoute = AppNobetHareketleriNewRouteImport.update({
  id: '/nobet-hareketleri_/new',
  path: '/nobet-hareketleri/new',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsAylikSatislarRoute = AppReportsAylikSatislarRouteImport.update({
  id: '/reports/aylikSatislar',
  path: '/reports/aylikSatislar',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsAylikSatislarMaliRoute =
  AppReportsAylikSatislarMaliRouteImport.update({
    id: '/reports/aylikSatislarMali',
    path: '/reports/aylikSatislarMali',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsCiroRoute = AppReportsCiroRouteImport.update({
  id: '/reports/ciro',
  path: '/reports/ciro',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsOrtakFaturalarRoute =
  AppReportsOrtakFaturalarRouteImport.update({
    id: '/reports/ortakFaturalar',
    path: '/reports/ortakFaturalar',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsStockRoute = AppReportsStockRouteImport.update({
  id: '/reports/stock',
  path: '/reports/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsTukenmeRoute = AppReportsTukenmeRouteImport.update({
  id: '/reports/tukenme',
  path: '/reports/tukenme',
  getParentRoute: () => AppRoute,
} as any)
const AppSatisStokHareketleriIdRoute =
  AppSatisStokHareketleriIdRouteImport.update({
    id: '/satis-stok-hareketleri_/$id',
    path: '/satis-stok-hareketleri/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppSatisStokHareketleriNewRoute =
  AppSatisStokHareketleriNewRouteImport.update({
    id: '/satis-stok-hareketleri_/new',
    path: '/satis-stok-hareketleri/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppSatisIdRoute = AppSatisIdRouteImport.update({
  id: '/satis_/$id',
  path: '/satis/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSatisNewRoute = AppSatisNewRouteImport.update({
  id: '/satis_/new',
  path: '/satis/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStokGirisiIdRoute = AppStokGirisiIdRouteImport.update({
  id: '/stok-girisi_/$id',
  path: '/stok-girisi/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStokGirisiNewRoute = AppStokGirisiNewRouteImport.update({
  id: '/stok-girisi_/new',
  path: '/stok-girisi/new',
  getParentRoute: () => AppRoute,
} as any)
const AppUreticiOdemeleriIdRoute = AppUreticiOdemeleriIdRouteImport.update({
  id: '/uretici-odemeleri_/$id',
  path: '/uretici-odemeleri/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUreticiOdemeleriNewRoute = AppUreticiOdemeleriNewRouteImport.update({
  id: '/uretici-odemeleri_/new',
  path: '/uretici-odemeleri/new',
  getParentRoute: () => AppRoute,
} as any)
const AppUreticiIdRoute = AppUreticiIdRouteImport.update({
  id: '/uretici_/$id',
  path: '/uretici/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUreticiNewRoute = AppUreticiNewRouteImport.update({
  id: '/uretici_/new',
  path: '/uretici/new',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunFiyatHesapIdRoute = AppUrunFiyatHesapIdRouteImport.update({
  id: '/urun-fiyat-hesap_/$id',
  path: '/urun-fiyat-hesap/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunFiyatHesapNewRoute = AppUrunFiyatHesapNewRouteImport.update({
  id: '/urun-fiyat-hesap_/new',
  path: '/urun-fiyat-hesap/new',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunFiyatIdRoute = AppUrunFiyatIdRouteImport.update({
  id: '/urun-fiyat_/$id',
  path: '/urun-fiyat/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunFiyatNewRoute = AppUrunFiyatNewRouteImport.update({
  id: '/urun-fiyat_/new',
  path: '/urun-fiyat/new',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunIdRoute = AppUrunIdRouteImport.update({
  id: '/urun_/$id',
  path: '/urun/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunNewRoute = AppUrunNewRouteImport.update({
  id: '/urun_/new',
  path: '/urun/new',
  getParentRoute: () => AppRoute,
} as any)
const AppVirmanIdRoute = AppVirmanIdRouteImport.update({
  id: '/virman_/$id',
  path: '/virman/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppVirmanNewRoute = AppVirmanNewRouteImport.update({
  id: '/virman_/new',
  path: '/virman/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountResetFinishRoute = AppAccountResetFinishRouteImport.update({
  id: '/account/reset/finish',
  path: '/account/reset/finish',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountResetRequestRoute = AppAccountResetRequestRouteImport.update({
  id: '/account/reset/request',
  path: '/account/reset/request',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUserManagementLoginRoute =
  AppAdminUserManagementLoginRouteImport.update({
    id: '/admin/user-management_/$login',
    path: '/admin/user-management/$login',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminUserManagementNewRoute =
  AppAdminUserManagementNewRouteImport.update({
    id: '/admin/user-management_/new',
    path: '/admin/user-management/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppBorcAlacakIdDeleteRoute = AppBorcAlacakIdDeleteRouteImport.update({
  id: '/borc-alacak_/$id_/delete',
  path: '/borc-alacak/$id/delete',
  getParentRoute: () => AppRoute,
} as any)
const AppBorcAlacakIdEditRoute = AppBorcAlacakIdEditRouteImport.update({
  id: '/borc-alacak_/$id_/edit',
  path: '/borc-alacak/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppGiderIdDeleteRoute = AppGiderIdDeleteRouteImport.update({
  id: '/gider_/$id_/delete',
  path: '/gider/$id/delete',
  getParentRoute: () => AppRoute,
} as any)
const AppGiderIdEditRoute = AppGiderIdEditRouteImport.update({
  id: '/gider_/$id_/edit',
  path: '/gider/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppKasaHareketleriIdDeleteRoute =
  AppKasaHareketleriIdDeleteRouteImport.update({
    id: '/kasa-hareketleri_/$id_/delete',
    path: '/kasa-hareketleri/$id/delete',
    getParentRoute: () => AppRoute,
  } as any)
const AppKasaHareketleriIdEditRoute =
  AppKasaHareketleriIdEditRouteImport.update({
    id: '/kasa-hareketleri_/$id_/edit',
    path: '/kasa-hareketleri/$id/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppKdvKategorisiIdDeleteRoute =
  AppKdvKategorisiIdDeleteRouteImport.update({
    id: '/kdv-kategorisi_/$id_/delete',
    path: '/kdv-kategorisi/$id/delete',
    getParentRoute: () => AppRoute,
  } as any)
const AppKdvKategorisiIdEditRoute = AppKdvKategorisiIdEditRouteImport.update({
  id: '/kdv-kategorisi_/$id_/edit',
  path: '/kdv-kategorisi/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppKisilerIdDeleteRoute = AppKisilerIdDeleteRouteImport.update({
  id: '/kisiler_/$id_/delete',
  path: '/kisiler/$id/delete',
  getParentRoute: () => AppRoute,
} as any)
const AppKisilerIdEditRoute = AppKisilerIdEditRouteImport.update({
  id: '/kisiler_/$id_/edit',
  path: '/kisiler/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppNobetHareketleriIdDeleteRoute =
  AppNobetHareketleriIdDeleteRouteImport.update({
    id: '/nobet-hareketleri_/$id_/delete',
    path: '/nobet-hareketleri/$id/delete',
    getParentRoute: () => AppRoute,
  } as any)
const AppNobetHareketleriIdEditRoute =
  AppNobetHareketleriIdEditRouteImport.update({
    id: '/nobet-hareketleri_/$id_/edit',
    path: '/nobet-hareketleri/$id/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsCiroIdRoute = AppReportsCiroIdRouteImport.update({
  id: '/reports/ciro_/$id',
  path: '/reports/ciro/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsOrtakFaturalarIdRoute =
  AppReportsOrtakFaturalarIdRouteImport.update({
    id: '/reports/ortakFaturalar_/$id',
    path: '/reports/ortakFaturalar/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppSatisStokHareketleriIdDeleteRoute =
  AppSatisStokHareketleriIdDeleteRouteImport.update({
    id: '/satis-stok-hareketleri_/$id_/delete',
    path: '/satis-stok-hareketleri/$id/delete',
    getParentRoute: () => AppRoute,
  } as any)
const AppSatisStokHareketleriIdEditRoute =
  AppSatisStokHareketleriIdEditRouteImport.update({
    id: '/satis-stok-hareketleri_/$id_/edit',
    path: '/satis-stok-hareketleri/$id/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppSatisIdDeleteRoute = AppSatisIdDeleteRouteImport.update({
  id: '/satis_/$id_/delete',
  path: '/satis/$id/delete',
  getParentRoute: () => AppRoute,
} as any)
const AppSatisIdEditRoute = AppSatisIdEditRouteImport.update({
  id: '/satis_/$id_/edit',
  path: '/satis/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppStokGirisiIdDeleteRoute = AppStokGirisiIdDeleteRouteImport.update({
  id: '/stok-girisi_/$id_/delete',
  path: '/stok-girisi/$id/delete',
  getParentRoute: () => AppRoute,
} as any)
const AppStokGirisiIdEditRoute = AppStokGirisiIdEditRouteImport.update({
  id: '/stok-girisi_/$id_/edit',
  path: '/stok-girisi/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppUreticiOdemeleriIdDeleteRoute =
  AppUreticiOdemeleriIdDeleteRouteImport.update({
    id: '/uretici-odemeleri_/$id_/delete',
    path: '/uretici-odemeleri/$id/delete',
    getParentRoute: () => AppRoute,
  } as any)
const AppUreticiOdemeleriIdEditRoute =
  AppUreticiOdemeleriIdEditRouteImport.update({
    id: '/uretici-odemeleri_/$id_/edit',
    path: '/uretici-odemeleri/$id/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppUreticiIdDeleteRoute = AppUreticiIdDeleteRouteImport.update({
  id: '/uretici_/$id_/delete',
  path: '/uretici/$id/delete',
  getParentRoute: () => AppRoute,
} as any)
const AppUreticiIdEditRoute = AppUreticiIdEditRouteImport.update({
  id: '/uretici_/$id_/edit',
  path: '/uretici/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunFiyatHesapIdDeleteRoute =
  AppUrunFiyatHesapIdDeleteRouteImport.update({
    id: '/urun-fiyat-hesap_/$id_/delete',
    path: '/urun-fiyat-hesap/$id/delete',
    getParentRoute: () => AppRoute,
  } as any)
const AppUrunFiyatHesapIdEditRoute = AppUrunFiyatHesapIdEditRouteImport.update({
  id: '/urun-fiyat-hesap_/$id_/edit',
  path: '/urun-fiyat-hesap/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunFiyatIdDeleteRoute = AppUrunFiyatIdDeleteRouteImport.update({
  id: '/urun-fiyat_/$id_/delete',
  path: '/urun-fiyat/$id/delete',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunFiyatIdEditRoute = AppUrunFiyatIdEditRouteImport.update({
  id: '/urun-fiyat_/$id_/edit',
  path: '/urun-fiyat/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunIdDeleteRoute = AppUrunIdDeleteRouteImport.update({
  id: '/urun_/$id_/delete',
  path: '/urun/$id/delete',
  getParentRoute: () => AppRoute,
} as any)
const AppUrunIdEditRoute = AppUrunIdEditRouteImport.update({
  id: '/urun_/$id_/edit',
  path: '/urun/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppVirmanIdDeleteRoute = AppVirmanIdDeleteRouteImport.update({
  id: '/virman_/$id_/delete',
  path: '/virman/$id/delete',
  getParentRoute: () => AppRoute,
} as any)
const AppVirmanIdEditRoute = AppVirmanIdEditRouteImport.update({
  id: '/virman_/$id_/edit',
  path: '/virman/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUserManagementLoginDeleteRoute =
  AppAdminUserManagementLoginDeleteRouteImport.update({
    id: '/admin/user-management_/$login_/delete',
    path: '/admin/user-management/$login/delete',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminUserManagementLoginEditRoute =
  AppAdminUserManagementLoginEditRouteImport.update({
    id: '/admin/user-management_/$login_/edit',
    path: '/admin/user-management/$login/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/$': typeof AppSplatRoute
  '/borc-alacak': typeof AppBorcAlacakRoute
  '/gider': typeof AppGiderRoute
  '/kasa-hareketleri': typeof AppKasaHareketleriRoute
  '/kdv-kategorisi': typeof AppKdvKategorisiRoute
  '/kisiler': typeof AppKisilerRoute
  '/login': typeof AppLoginRoute
  '/logout': typeof AppLogoutRoute
  '/nobet-hareketleri': typeof AppNobetHareketleriRoute
  '/satis': typeof AppSatisRoute
  '/satis-stok-hareketleri': typeof AppSatisStokHareketleriRoute
  '/stok-girisi': typeof AppStokGirisiRoute
  '/uretici': typeof AppUreticiRoute
  '/uretici-odemeleri': typeof AppUreticiOdemeleriRoute
  '/urun': typeof AppUrunRoute
  '/urun-fiyat': typeof AppUrunFiyatRoute
  '/urun-fiyat-hesap': typeof AppUrunFiyatHesapRoute
  '/virman': typeof AppVirmanRoute
  '/account/activate': typeof AppAccountActivateRoute
  '/account/password': typeof AppAccountPasswordRoute
  '/account/settings': typeof AppAccountSettingsRoute
  '/admin/audits': typeof AppAdminAuditsRoute
  '/admin/health': typeof AppAdminHealthRoute
  '/admin/operations': typeof AppAdminOperationsRoute
  '/admin/user-management': typeof AppAdminUserManagementRoute
  '/borc-alacak/$id': typeof AppBorcAlacakIdRoute
  '/borc-alacak/new': typeof AppBorcAlacakNewRoute
  '/gider/$id': typeof AppGiderIdRoute
  '/gider/new': typeof AppGiderNewRoute
  '/kasa-hareketleri/$id': typeof AppKasaHareketleriIdRoute
  '/kasa-hareketleri/new': typeof AppKasaHareketleriNewRoute
  '/kdv-kategorisi/$id': typeof AppKdvKategorisiIdRoute
  '/kdv-kategorisi/new': typeof AppKdvKategorisiNewRoute
  '/kisiler/$id': typeof AppKisilerIdRoute
  '/kisiler/new': typeof AppKisilerNewRoute
  '/nobet-hareketleri/$id': typeof AppNobetHareketleriIdRoute
  '/nobet-hareketleri/new': typeof AppNobetHareketleriNewRoute
  '/reports/aylikSatislar': typeof AppReportsAylikSatislarRoute
  '/reports/aylikSatislarMali': typeof AppReportsAylikSatislarMaliRoute
  '/reports/ciro': typeof AppReportsCiroRoute
  '/reports/ortakFaturalar': typeof AppReportsOrtakFaturalarRoute
  '/reports/stock': typeof AppReportsStockRoute
  '/reports/tukenme': typeof AppReportsTukenmeRoute
  '/satis-stok-hareketleri/$id': typeof AppSatisStokHareketleriIdRoute
  '/satis-stok-hareketleri/new': typeof AppSatisStokHareketleriNewRoute
  '/satis/$id': typeof AppSatisIdRoute
  '/satis/new': typeof AppSatisNewRoute
  '/stok-girisi/$id': typeof AppStokGirisiIdRoute
  '/stok-girisi/new': typeof AppStokGirisiNewRoute
  '/uretici-odemeleri/$id': typeof AppUreticiOdemeleriIdRoute
  '/uretici-odemeleri/new': typeof AppUreticiOdemeleriNewRoute
  '/uretici/$id': typeof AppUreticiIdRoute
  '/uretici/new': typeof AppUreticiNewRoute
  '/urun-fiyat-hesap/$id': typeof AppUrunFiyatHesapIdRoute
  '/urun-fiyat-hesap/new': typeof AppUrunFiyatHesapNewRoute
  '/urun-fiyat/$id': typeof AppUrunFiyatIdRoute
  '/urun-fiyat/new': typeof AppUrunFiyatNewRoute
  '/urun/$id': typeof AppUrunIdRoute
  '/urun/new': typeof AppUrunNewRoute
  '/virman/$id': typeof AppVirmanIdRoute
  '/virman/new': typeof AppVirmanNewRoute
  '/account/reset/finish': typeof AppAccountResetFinishRoute
  '/account/reset/request': typeof AppAccountResetRequestRoute
  '/admin/user-management/$login': typeof AppAdminUserManagementLoginRoute
  '/admin/user-management/new': typeof AppAdminUserManagementNewRoute
  '/borc-alacak/$id/delete': typeof AppBorcAlacakIdDeleteRoute
  '/borc-alacak/$id/edit': typeof AppBorcAlacakIdEditRoute
  '/gider/$id/delete': typeof AppGiderIdDeleteRoute
  '/gider/$id/edit': typeof AppGiderIdEditRoute
  '/kasa-hareketleri/$id/delete': typeof AppKasaHareketleriIdDeleteRoute
  '/kasa-hareketleri/$id/edit': typeof AppKasaHareketleriIdEditRoute
  '/kdv-kategorisi/$id/delete': typeof AppKdvKategorisiIdDeleteRoute
  '/kdv-kategorisi/$id/edit': typeof AppKdvKategorisiIdEditRoute
  '/kisiler/$id/delete': typeof AppKisilerIdDeleteRoute
  '/kisiler/$id/edit': typeof AppKisilerIdEditRoute
  '/nobet-hareketleri/$id/delete': typeof AppNobetHareketleriIdDeleteRoute
  '/nobet-hareketleri/$id/edit': typeof AppNobetHareketleriIdEditRoute
  '/reports/ciro/$id': typeof AppReportsCiroIdRoute
  '/reports/ortakFaturalar/$id': typeof AppReportsOrtakFaturalarIdRoute
  '/satis-stok-hareketleri/$id/delete': typeof AppSatisStokHareketleriIdDeleteRoute
  '/satis-stok-hareketleri/$id/edit': typeof AppSatisStokHareketleriIdEditRoute
  '/satis/$id/delete': typeof AppSatisIdDeleteRoute
  '/satis/$id/edit': typeof AppSatisIdEditRoute
  '/stok-girisi/$id/delete': typeof AppStokGirisiIdDeleteRoute
  '/stok-girisi/$id/edit': typeof AppStokGirisiIdEditRoute
  '/uretici-odemeleri/$id/delete': typeof AppUreticiOdemeleriIdDeleteRoute
  '/uretici-odemeleri/$id/edit': typeof AppUreticiOdemeleriIdEditRoute
  '/uretici/$id/delete': typeof AppUreticiIdDeleteRoute
  '/uretici/$id/edit': typeof AppUreticiIdEditRoute
  '/urun-fiyat-hesap/$id/delete': typeof AppUrunFiyatHesapIdDeleteRoute
  '/urun-fiyat-hesap/$id/edit': typeof AppUrunFiyatHesapIdEditRoute
  '/urun-fiyat/$id/delete': typeof AppUrunFiyatIdDeleteRoute
  '/urun-fiyat/$id/edit': typeof AppUrunFiyatIdEditRoute
  '/urun/$id/delete': typeof AppUrunIdDeleteRoute
  '/urun/$id/edit': typeof AppUrunIdEditRoute
  '/virman/$id/delete': typeof AppVirmanIdDeleteRoute
  '/virman/$id/edit': typeof AppVirmanIdEditRoute
  '/admin/user-management/$login/delete': typeof AppAdminUserManagementLoginDeleteRoute
  '/admin/user-management/$login/edit': typeof AppAdminUserManagementLoginEditRoute
}
export interface FileRoutesByTo {
  '/$': typeof AppSplatRoute
  '/borc-alacak': typeof AppBorcAlacakRoute
  '/gider': typeof AppGiderRoute
  '/kasa-hareketleri': typeof AppKasaHareketleriRoute
  '/kdv-kategorisi': typeof AppKdvKategorisiRoute
  '/kisiler': typeof AppKisilerRoute
  '/login': typeof AppLoginRoute
  '/logout': typeof AppLogoutRoute
  '/nobet-hareketleri': typeof AppNobetHareketleriRoute
  '/satis': typeof AppSatisRoute
  '/satis-stok-hareketleri': typeof AppSatisStokHareketleriRoute
  '/stok-girisi': typeof AppStokGirisiRoute
  '/uretici': typeof AppUreticiRoute
  '/uretici-odemeleri': typeof AppUreticiOdemeleriRoute
  '/urun': typeof AppUrunRoute
  '/urun-fiyat': typeof AppUrunFiyatRoute
  '/urun-fiyat-hesap': typeof AppUrunFiyatHesapRoute
  '/virman': typeof AppVirmanRoute
  '/': typeof AppIndexRoute
  '/account/activate': typeof AppAccountActivateRoute
  '/account/password': typeof AppAccountPasswordRoute
  '/account/settings': typeof AppAccountSettingsRoute
  '/admin/audits': typeof AppAdminAuditsRoute
  '/admin/health': typeof AppAdminHealthRoute
  '/admin/operations': typeof AppAdminOperationsRoute
  '/admin/user-management': typeof AppAdminUserManagementRoute
  '/borc-alacak/$id': typeof AppBorcAlacakIdRoute
  '/borc-alacak/new': typeof AppBorcAlacakNewRoute
  '/gider/$id': typeof AppGiderIdRoute
  '/gider/new': typeof AppGiderNewRoute
  '/kasa-hareketleri/$id': typeof AppKasaHareketleriIdRoute
  '/kasa-hareketleri/new': typeof AppKasaHareketleriNewRoute
  '/kdv-kategorisi/$id': typeof AppKdvKategorisiIdRoute
  '/kdv-kategorisi/new': typeof AppKdvKategorisiNewRoute
  '/kisiler/$id': typeof AppKisilerIdRoute
  '/kisiler/new': typeof AppKisilerNewRoute
  '/nobet-hareketleri/$id': typeof AppNobetHareketleriIdRoute
  '/nobet-hareketleri/new': typeof AppNobetHareketleriNewRoute
  '/reports/aylikSatislar': typeof AppReportsAylikSatislarRoute
  '/reports/aylikSatislarMali': typeof AppReportsAylikSatislarMaliRoute
  '/reports/ciro': typeof AppReportsCiroRoute
  '/reports/ortakFaturalar': typeof AppReportsOrtakFaturalarRoute
  '/reports/stock': typeof AppReportsStockRoute
  '/reports/tukenme': typeof AppReportsTukenmeRoute
  '/satis-stok-hareketleri/$id': typeof AppSatisStokHareketleriIdRoute
  '/satis-stok-hareketleri/new': typeof AppSatisStokHareketleriNewRoute
  '/satis/$id': typeof AppSatisIdRoute
  '/satis/new': typeof AppSatisNewRoute
  '/stok-girisi/$id': typeof AppStokGirisiIdRoute
  '/stok-girisi/new': typeof AppStokGirisiNewRoute
  '/uretici-odemeleri/$id': typeof AppUreticiOdemeleriIdRoute
  '/uretici-odemeleri/new': typeof AppUreticiOdemeleriNewRoute
  '/uretici/$id': typeof AppUreticiIdRoute
  '/uretici/new': typeof AppUreticiNewRoute
  '/urun-fiyat-hesap/$id': typeof AppUrunFiyatHesapIdRoute
  '/urun-fiyat-hesap/new': typeof AppUrunFiyatHesapNewRoute
  '/urun-fiyat/$id': typeof AppUrunFiyatIdRoute
  '/urun-fiyat/new': typeof AppUrunFiyatNewRoute
  '/urun/$id': typeof AppUrunIdRoute
  '/urun/new': typeof AppUrunNewRoute
  '/virman/$id': typeof AppVirmanIdRoute
  '/virman/new': typeof AppVirmanNewRoute
  '/account/reset/finish': typeof AppAccountResetFinishRoute
  '/account/reset/request': typeof AppAccountResetRequestRoute
  '/admin/user-management/$login': typeof AppAdminUserManagementLoginRoute
  '/admin/user-management/new': typeof AppAdminUserManagementNewRoute
  '/borc-alacak/$id/delete': typeof AppBorcAlacakIdDeleteRoute
  '/borc-alacak/$id/edit': typeof AppBorcAlacakIdEditRoute
  '/gider/$id/delete': typeof AppGiderIdDeleteRoute
  '/gider/$id/edit': typeof AppGiderIdEditRoute
  '/kasa-hareketleri/$id/delete': typeof AppKasaHareketleriIdDeleteRoute
  '/kasa-hareketleri/$id/edit': typeof AppKasaHareketleriIdEditRoute
  '/kdv-kategorisi/$id/delete': typeof AppKdvKategorisiIdDeleteRoute
  '/kdv-kategorisi/$id/edit': typeof AppKdvKategorisiIdEditRoute
  '/kisiler/$id/delete': typeof AppKisilerIdDeleteRoute
  '/kisiler/$id/edit': typeof AppKisilerIdEditRoute
  '/nobet-hareketleri/$id/delete': typeof AppNobetHareketleriIdDeleteRoute
  '/nobet-hareketleri/$id/edit': typeof AppNobetHareketleriIdEditRoute
  '/reports/ciro/$id': typeof AppReportsCiroIdRoute
  '/reports/ortakFaturalar/$id': typeof AppReportsOrtakFaturalarIdRoute
  '/satis-stok-hareketleri/$id/delete': typeof AppSatisStokHareketleriIdDeleteRoute
  '/satis-stok-hareketleri/$id/edit': typeof AppSatisStokHareketleriIdEditRoute
  '/satis/$id/delete': typeof AppSatisIdDeleteRoute
  '/satis/$id/edit': typeof AppSatisIdEditRoute
  '/stok-girisi/$id/delete': typeof AppStokGirisiIdDeleteRoute
  '/stok-girisi/$id/edit': typeof AppStokGirisiIdEditRoute
  '/uretici-odemeleri/$id/delete': typeof AppUreticiOdemeleriIdDeleteRoute
  '/uretici-odemeleri/$id/edit': typeof AppUreticiOdemeleriIdEditRoute
  '/uretici/$id/delete': typeof AppUreticiIdDeleteRoute
  '/uretici/$id/edit': typeof AppUreticiIdEditRoute
  '/urun-fiyat-hesap/$id/delete': typeof AppUrunFiyatHesapIdDeleteRoute
  '/urun-fiyat-hesap/$id/edit': typeof AppUrunFiyatHesapIdEditRoute
  '/urun-fiyat/$id/delete': typeof AppUrunFiyatIdDeleteRoute
  '/urun-fiyat/$id/edit': typeof AppUrunFiyatIdEditRoute
  '/urun/$id/delete': typeof AppUrunIdDeleteRoute
  '/urun/$id/edit': typeof AppUrunIdEditRoute
  '/virman/$id/delete': typeof AppVirmanIdDeleteRoute
  '/virman/$id/edit': typeof AppVirmanIdEditRoute
  '/admin/user-management/$login/delete': typeof AppAdminUserManagementLoginDeleteRoute
  '/admin/user-management/$login/edit': typeof AppAdminUserManagementLoginEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_app/borc-alacak': typeof AppBorcAlacakRoute
  '/_app/gider': typeof AppGiderRoute
  '/_app/kasa-hareketleri': typeof AppKasaHareketleriRoute
  '/_app/kdv-kategorisi': typeof AppKdvKategorisiRoute
  '/_app/kisiler': typeof AppKisilerRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/logout': typeof AppLogoutRoute
  '/_app/nobet-hareketleri': typeof AppNobetHareketleriRoute
  '/_app/satis': typeof AppSatisRoute
  '/_app/satis-stok-hareketleri': typeof AppSatisStokHareketleriRoute
  '/_app/stok-girisi': typeof AppStokGirisiRoute
  '/_app/uretici': typeof AppUreticiRoute
  '/_app/uretici-odemeleri': typeof AppUreticiOdemeleriRoute
  '/_app/urun': typeof AppUrunRoute
  '/_app/urun-fiyat': typeof AppUrunFiyatRoute
  '/_app/urun-fiyat-hesap': typeof AppUrunFiyatHesapRoute
  '/_app/virman': typeof AppVirmanRoute
  '/_app/': typeof AppIndexRoute
  '/_app/account/activate': typeof AppAccountActivateRoute
  '/_app/account/password': typeof AppAccountPasswordRoute
  '/_app/account/settings': typeof AppAccountSettingsRoute
  '/_app/admin/audits': typeof AppAdminAuditsRoute
  '/_app/admin/health': typeof AppAdminHealthRoute
  '/_app/admin/operations': typeof AppAdminOperationsRoute
  '/_app/admin/user-management': typeof AppAdminUserManagementRoute
  '/_app/borc-alacak_/$id': typeof AppBorcAlacakIdRoute
  '/_app/borc-alacak_/new': typeof AppBorcAlacakNewRoute
  '/_app/gider_/$id': typeof AppGiderIdRoute
  '/_app/gider_/new': typeof AppGiderNewRoute
  '/_app/kasa-hareketleri_/$id': typeof AppKasaHareketleriIdRoute
  '/_app/kasa-hareketleri_/new': typeof AppKasaHareketleriNewRoute
  '/_app/kdv-kategorisi_/$id': typeof AppKdvKategorisiIdRoute
  '/_app/kdv-kategorisi_/new': typeof AppKdvKategorisiNewRoute
  '/_app/kisiler_/$id': typeof AppKisilerIdRoute
  '/_app/kisiler_/new': typeof AppKisilerNewRoute
  '/_app/nobet-hareketleri_/$id': typeof AppNobetHareketleriIdRoute
  '/_app/nobet-hareketleri_/new': typeof AppNobetHareketleriNewRoute
  '/_app/reports/aylikSatislar': typeof AppReportsAylikSatislarRoute
  '/_app/reports/aylikSatislarMali': typeof AppReportsAylikSatislarMaliRoute
  '/_app/reports/ciro': typeof AppReportsCiroRoute
  '/_app/reports/ortakFaturalar': typeof AppReportsOrtakFaturalarRoute
  '/_app/reports/stock': typeof AppReportsStockRoute
  '/_app/reports/tukenme': typeof AppReportsTukenmeRoute
  '/_app/satis-stok-hareketleri_/$id': typeof AppSatisStokHareketleriIdRoute
  '/_app/satis-stok-hareketleri_/new': typeof AppSatisStokHareketleriNewRoute
  '/_app/satis_/$id': typeof AppSatisIdRoute
  '/_app/satis_/new': typeof AppSatisNewRoute
  '/_app/stok-girisi_/$id': typeof AppStokGirisiIdRoute
  '/_app/stok-girisi_/new': typeof AppStokGirisiNewRoute
  '/_app/uretici-odemeleri_/$id': typeof AppUreticiOdemeleriIdRoute
  '/_app/uretici-odemeleri_/new': typeof AppUreticiOdemeleriNewRoute
  '/_app/uretici_/$id': typeof AppUreticiIdRoute
  '/_app/uretici_/new': typeof AppUreticiNewRoute
  '/_app/urun-fiyat-hesap_/$id': typeof AppUrunFiyatHesapIdRoute
  '/_app/urun-fiyat-hesap_/new': typeof AppUrunFiyatHesapNewRoute
  '/_app/urun-fiyat_/$id': typeof AppUrunFiyatIdRoute
  '/_app/urun-fiyat_/new': typeof AppUrunFiyatNewRoute
  '/_app/urun_/$id': typeof AppUrunIdRoute
  '/_app/urun_/new': typeof AppUrunNewRoute
  '/_app/virman_/$id': typeof AppVirmanIdRoute
  '/_app/virman_/new': typeof AppVirmanNewRoute
  '/_app/account/reset/finish': typeof AppAccountResetFinishRoute
  '/_app/account/reset/request': typeof AppAccountResetRequestRoute
  '/_app/admin/user-management_/$login': typeof AppAdminUserManagementLoginRoute
  '/_app/admin/user-management_/new': typeof AppAdminUserManagementNewRoute
  '/_app/borc-alacak_/$id_/delete': typeof AppBorcAlacakIdDeleteRoute
  '/_app/borc-alacak_/$id_/edit': typeof AppBorcAlacakIdEditRoute
  '/_app/gider_/$id_/delete': typeof AppGiderIdDeleteRoute
  '/_app/gider_/$id_/edit': typeof AppGiderIdEditRoute
  '/_app/kasa-hareketleri_/$id_/delete': typeof AppKasaHareketleriIdDeleteRoute
  '/_app/kasa-hareketleri_/$id_/edit': typeof AppKasaHareketleriIdEditRoute
  '/_app/kdv-kategorisi_/$id_/delete': typeof AppKdvKategorisiIdDeleteRoute
  '/_app/kdv-kategorisi_/$id_/edit': typeof AppKdvKategorisiIdEditRoute
  '/_app/kisiler_/$id_/delete': typeof AppKisilerIdDeleteRoute
  '/_app/kisiler_/$id_/edit': typeof AppKisilerIdEditRoute
  '/_app/nobet-hareketleri_/$id_/delete': typeof AppNobetHareketleriIdDeleteRoute
  '/_app/nobet-hareketleri_/$id_/edit': typeof AppNobetHareketleriIdEditRoute
  '/_app/reports/ciro_/$id': typeof AppReportsCiroIdRoute
  '/_app/reports/ortakFaturalar_/$id': typeof AppReportsOrtakFaturalarIdRoute
  '/_app/satis-stok-hareketleri_/$id_/delete': typeof AppSatisStokHareketleriIdDeleteRoute
  '/_app/satis-stok-hareketleri_/$id_/edit': typeof AppSatisStokHareketleriIdEditRoute
  '/_app/satis_/$id_/delete': typeof AppSatisIdDeleteRoute
  '/_app/satis_/$id_/edit': typeof AppSatisIdEditRoute
  '/_app/stok-girisi_/$id_/delete': typeof AppStokGirisiIdDeleteRoute
  '/_app/stok-girisi_/$id_/edit': typeof AppStokGirisiIdEditRoute
  '/_app/uretici-odemeleri_/$id_/delete': typeof AppUreticiOdemeleriIdDeleteRoute
  '/_app/uretici-odemeleri_/$id_/edit': typeof AppUreticiOdemeleriIdEditRoute
  '/_app/uretici_/$id_/delete': typeof AppUreticiIdDeleteRoute
  '/_app/uretici_/$id_/edit': typeof AppUreticiIdEditRoute
  '/_app/urun-fiyat-hesap_/$id_/delete': typeof AppUrunFiyatHesapIdDeleteRoute
  '/_app/urun-fiyat-hesap_/$id_/edit': typeof AppUrunFiyatHesapIdEditRoute
  '/_app/urun-fiyat_/$id_/delete': typeof AppUrunFiyatIdDeleteRoute
  '/_app/urun-fiyat_/$id_/edit': typeof AppUrunFiyatIdEditRoute
  '/_app/urun_/$id_/delete': typeof AppUrunIdDeleteRoute
  '/_app/urun_/$id_/edit': typeof AppUrunIdEditRoute
  '/_app/virman_/$id_/delete': typeof AppVirmanIdDeleteRoute
  '/_app/virman_/$id_/edit': typeof AppVirmanIdEditRoute
  '/_app/admin/user-management_/$login_/delete': typeof AppAdminUserManagementLoginDeleteRoute
  '/_app/admin/user-management_/$login_/edit': typeof AppAdminUserManagementLoginEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/borc-alacak'
    | '/gider'
    | '/kasa-hareketleri'
    | '/kdv-kategorisi'
    | '/kisiler'
    | '/login'
    | '/logout'
    | '/nobet-hareketleri'
    | '/satis'
    | '/satis-stok-hareketleri'
    | '/stok-girisi'
    | '/uretici'
    | '/uretici-odemeleri'
    | '/urun'
    | '/urun-fiyat'
    | '/urun-fiyat-hesap'
    | '/virman'
    | '/account/activate'
    | '/account/password'
    | '/account/settings'
    | '/admin/audits'
    | '/admin/health'
    | '/admin/operations'
    | '/admin/user-management'
    | '/borc-alacak/$id'
    | '/borc-alacak/new'
    | '/gider/$id'
    | '/gider/new'
    | '/kasa-hareketleri/$id'
    | '/kasa-hareketleri/new'
    | '/kdv-kategorisi/$id'
    | '/kdv-kategorisi/new'
    | '/kisiler/$id'
    | '/kisiler/new'
    | '/nobet-hareketleri/$id'
    | '/nobet-hareketleri/new'
    | '/reports/aylikSatislar'
    | '/reports/aylikSatislarMali'
    | '/reports/ciro'
    | '/reports/ortakFaturalar'
    | '/reports/stock'
    | '/reports/tukenme'
    | '/satis-stok-hareketleri/$id'
    | '/satis-stok-hareketleri/new'
    | '/satis/$id'
    | '/satis/new'
    | '/stok-girisi/$id'
    | '/stok-girisi/new'
    | '/uretici-odemeleri/$id'
    | '/uretici-odemeleri/new'
    | '/uretici/$id'
    | '/uretici/new'
    | '/urun-fiyat-hesap/$id'
    | '/urun-fiyat-hesap/new'
    | '/urun-fiyat/$id'
    | '/urun-fiyat/new'
    | '/urun/$id'
    | '/urun/new'
    | '/virman/$id'
    | '/virman/new'
    | '/account/reset/finish'
    | '/account/reset/request'
    | '/admin/user-management/$login'
    | '/admin/user-management/new'
    | '/borc-alacak/$id/delete'
    | '/borc-alacak/$id/edit'
    | '/gider/$id/delete'
    | '/gider/$id/edit'
    | '/kasa-hareketleri/$id/delete'
    | '/kasa-hareketleri/$id/edit'
    | '/kdv-kategorisi/$id/delete'
    | '/kdv-kategorisi/$id/edit'
    | '/kisiler/$id/delete'
    | '/kisiler/$id/edit'
    | '/nobet-hareketleri/$id/delete'
    | '/nobet-hareketleri/$id/edit'
    | '/reports/ciro/$id'
    | '/reports/ortakFaturalar/$id'
    | '/satis-stok-hareketleri/$id/delete'
    | '/satis-stok-hareketleri/$id/edit'
    | '/satis/$id/delete'
    | '/satis/$id/edit'
    | '/stok-girisi/$id/delete'
    | '/stok-girisi/$id/edit'
    | '/uretici-odemeleri/$id/delete'
    | '/uretici-odemeleri/$id/edit'
    | '/uretici/$id/delete'
    | '/uretici/$id/edit'
    | '/urun-fiyat-hesap/$id/delete'
    | '/urun-fiyat-hesap/$id/edit'
    | '/urun-fiyat/$id/delete'
    | '/urun-fiyat/$id/edit'
    | '/urun/$id/delete'
    | '/urun/$id/edit'
    | '/virman/$id/delete'
    | '/virman/$id/edit'
    | '/admin/user-management/$login/delete'
    | '/admin/user-management/$login/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/borc-alacak'
    | '/gider'
    | '/kasa-hareketleri'
    | '/kdv-kategorisi'
    | '/kisiler'
    | '/login'
    | '/logout'
    | '/nobet-hareketleri'
    | '/satis'
    | '/satis-stok-hareketleri'
    | '/stok-girisi'
    | '/uretici'
    | '/uretici-odemeleri'
    | '/urun'
    | '/urun-fiyat'
    | '/urun-fiyat-hesap'
    | '/virman'
    | '/'
    | '/account/activate'
    | '/account/password'
    | '/account/settings'
    | '/admin/audits'
    | '/admin/health'
    | '/admin/operations'
    | '/admin/user-management'
    | '/borc-alacak/$id'
    | '/borc-alacak/new'
    | '/gider/$id'
    | '/gider/new'
    | '/kasa-hareketleri/$id'
    | '/kasa-hareketleri/new'
    | '/kdv-kategorisi/$id'
    | '/kdv-kategorisi/new'
    | '/kisiler/$id'
    | '/kisiler/new'
    | '/nobet-hareketleri/$id'
    | '/nobet-hareketleri/new'
    | '/reports/aylikSatislar'
    | '/reports/aylikSatislarMali'
    | '/reports/ciro'
    | '/reports/ortakFaturalar'
    | '/reports/stock'
    | '/reports/tukenme'
    | '/satis-stok-hareketleri/$id'
    | '/satis-stok-hareketleri/new'
    | '/satis/$id'
    | '/satis/new'
    | '/stok-girisi/$id'
    | '/stok-girisi/new'
    | '/uretici-odemeleri/$id'
    | '/uretici-odemeleri/new'
    | '/uretici/$id'
    | '/uretici/new'
    | '/urun-fiyat-hesap/$id'
    | '/urun-fiyat-hesap/new'
    | '/urun-fiyat/$id'
    | '/urun-fiyat/new'
    | '/urun/$id'
    | '/urun/new'
    | '/virman/$id'
    | '/virman/new'
    | '/account/reset/finish'
    | '/account/reset/request'
    | '/admin/user-management/$login'
    | '/admin/user-management/new'
    | '/borc-alacak/$id/delete'
    | '/borc-alacak/$id/edit'
    | '/gider/$id/delete'
    | '/gider/$id/edit'
    | '/kasa-hareketleri/$id/delete'
    | '/kasa-hareketleri/$id/edit'
    | '/kdv-kategorisi/$id/delete'
    | '/kdv-kategorisi/$id/edit'
    | '/kisiler/$id/delete'
    | '/kisiler/$id/edit'
    | '/nobet-hareketleri/$id/delete'
    | '/nobet-hareketleri/$id/edit'
    | '/reports/ciro/$id'
    | '/reports/ortakFaturalar/$id'
    | '/satis-stok-hareketleri/$id/delete'
    | '/satis-stok-hareketleri/$id/edit'
    | '/satis/$id/delete'
    | '/satis/$id/edit'
    | '/stok-girisi/$id/delete'
    | '/stok-girisi/$id/edit'
    | '/uretici-odemeleri/$id/delete'
    | '/uretici-odemeleri/$id/edit'
    | '/uretici/$id/delete'
    | '/uretici/$id/edit'
    | '/urun-fiyat-hesap/$id/delete'
    | '/urun-fiyat-hesap/$id/edit'
    | '/urun-fiyat/$id/delete'
    | '/urun-fiyat/$id/edit'
    | '/urun/$id/delete'
    | '/urun/$id/edit'
    | '/virman/$id/delete'
    | '/virman/$id/edit'
    | '/admin/user-management/$login/delete'
    | '/admin/user-management/$login/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_app/$'
    | '/_app/borc-alacak'
    | '/_app/gider'
    | '/_app/kasa-hareketleri'
    | '/_app/kdv-kategorisi'
    | '/_app/kisiler'
    | '/_app/login'
    | '/_app/logout'
    | '/_app/nobet-hareketleri'
    | '/_app/satis'
    | '/_app/satis-stok-hareketleri'
    | '/_app/stok-girisi'
    | '/_app/uretici'
    | '/_app/uretici-odemeleri'
    | '/_app/urun'
    | '/_app/urun-fiyat'
    | '/_app/urun-fiyat-hesap'
    | '/_app/virman'
    | '/_app/'
    | '/_app/account/activate'
    | '/_app/account/password'
    | '/_app/account/settings'
    | '/_app/admin/audits'
    | '/_app/admin/health'
    | '/_app/admin/operations'
    | '/_app/admin/user-management'
    | '/_app/borc-alacak_/$id'
    | '/_app/borc-alacak_/new'
    | '/_app/gider_/$id'
    | '/_app/gider_/new'
    | '/_app/kasa-hareketleri_/$id'
    | '/_app/kasa-hareketleri_/new'
    | '/_app/kdv-kategorisi_/$id'
    | '/_app/kdv-kategorisi_/new'
    | '/_app/kisiler_/$id'
    | '/_app/kisiler_/new'
    | '/_app/nobet-hareketleri_/$id'
    | '/_app/nobet-hareketleri_/new'
    | '/_app/reports/aylikSatislar'
    | '/_app/reports/aylikSatislarMali'
    | '/_app/reports/ciro'
    | '/_app/reports/ortakFaturalar'
    | '/_app/reports/stock'
    | '/_app/reports/tukenme'
    | '/_app/satis-stok-hareketleri_/$id'
    | '/_app/satis-stok-hareketleri_/new'
    | '/_app/satis_/$id'
    | '/_app/satis_/new'
    | '/_app/stok-girisi_/$id'
    | '/_app/stok-girisi_/new'
    | '/_app/uretici-odemeleri_/$id'
    | '/_app/uretici-odemeleri_/new'
    | '/_app/uretici_/$id'
    | '/_app/uretici_/new'
    | '/_app/urun-fiyat-hesap_/$id'
    | '/_app/urun-fiyat-hesap_/new'
    | '/_app/urun-fiyat_/$id'
    | '/_app/urun-fiyat_/new'
    | '/_app/urun_/$id'
    | '/_app/urun_/new'
    | '/_app/virman_/$id'
    | '/_app/virman_/new'
    | '/_app/account/reset/finish'
    | '/_app/account/reset/request'
    | '/_app/admin/user-management_/$login'
    | '/_app/admin/user-management_/new'
    | '/_app/borc-alacak_/$id_/delete'
    | '/_app/borc-alacak_/$id_/edit'
    | '/_app/gider_/$id_/delete'
    | '/_app/gider_/$id_/edit'
    | '/_app/kasa-hareketleri_/$id_/delete'
    | '/_app/kasa-hareketleri_/$id_/edit'
    | '/_app/kdv-kategorisi_/$id_/delete'
    | '/_app/kdv-kategorisi_/$id_/edit'
    | '/_app/kisiler_/$id_/delete'
    | '/_app/kisiler_/$id_/edit'
    | '/_app/nobet-hareketleri_/$id_/delete'
    | '/_app/nobet-hareketleri_/$id_/edit'
    | '/_app/reports/ciro_/$id'
    | '/_app/reports/ortakFaturalar_/$id'
    | '/_app/satis-stok-hareketleri_/$id_/delete'
    | '/_app/satis-stok-hareketleri_/$id_/edit'
    | '/_app/satis_/$id_/delete'
    | '/_app/satis_/$id_/edit'
    | '/_app/stok-girisi_/$id_/delete'
    | '/_app/stok-girisi_/$id_/edit'
    | '/_app/uretici-odemeleri_/$id_/delete'
    | '/_app/uretici-odemeleri_/$id_/edit'
    | '/_app/uretici_/$id_/delete'
    | '/_app/uretici_/$id_/edit'
    | '/_app/urun-fiyat-hesap_/$id_/delete'
    | '/_app/urun-fiyat-hesap_/$id_/edit'
    | '/_app/urun-fiyat_/$id_/delete'
    | '/_app/urun-fiyat_/$id_/edit'
    | '/_app/urun_/$id_/delete'
    | '/_app/urun_/$id_/edit'
    | '/_app/virman_/$id_/delete'
    | '/_app/virman_/$id_/edit'
    | '/_app/admin/user-management_/$login_/delete'
    | '/_app/admin/user-management_/$login_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/borc-alacak': {
      id: '/_app/borc-alacak'
      path: '/borc-alacak'
      fullPath: '/borc-alacak'
      preLoaderRoute: typeof AppBorcAlacakRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gider': {
      id: '/_app/gider'
      path: '/gider'
      fullPath: '/gider'
      preLoaderRoute: typeof AppGiderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kasa-hareketleri': {
      id: '/_app/kasa-hareketleri'
      path: '/kasa-hareketleri'
      fullPath: '/kasa-hareketleri'
      preLoaderRoute: typeof AppKasaHareketleriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kdv-kategorisi': {
      id: '/_app/kdv-kategorisi'
      path: '/kdv-kategorisi'
      fullPath: '/kdv-kategorisi'
      preLoaderRoute: typeof AppKdvKategorisiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kisiler': {
      id: '/_app/kisiler'
      path: '/kisiler'
      fullPath: '/kisiler'
      preLoaderRoute: typeof AppKisilerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logout': {
      id: '/_app/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AppLogoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nobet-hareketleri': {
      id: '/_app/nobet-hareketleri'
      path: '/nobet-hareketleri'
      fullPath: '/nobet-hareketleri'
      preLoaderRoute: typeof AppNobetHareketleriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satis': {
      id: '/_app/satis'
      path: '/satis'
      fullPath: '/satis'
      preLoaderRoute: typeof AppSatisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satis-stok-hareketleri': {
      id: '/_app/satis-stok-hareketleri'
      path: '/satis-stok-hareketleri'
      fullPath: '/satis-stok-hareketleri'
      preLoaderRoute: typeof AppSatisStokHareketleriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stok-girisi': {
      id: '/_app/stok-girisi'
      path: '/stok-girisi'
      fullPath: '/stok-girisi'
      preLoaderRoute: typeof AppStokGirisiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uretici': {
      id: '/_app/uretici'
      path: '/uretici'
      fullPath: '/uretici'
      preLoaderRoute: typeof AppUreticiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uretici-odemeleri': {
      id: '/_app/uretici-odemeleri'
      path: '/uretici-odemeleri'
      fullPath: '/uretici-odemeleri'
      preLoaderRoute: typeof AppUreticiOdemeleriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun': {
      id: '/_app/urun'
      path: '/urun'
      fullPath: '/urun'
      preLoaderRoute: typeof AppUrunRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun-fiyat': {
      id: '/_app/urun-fiyat'
      path: '/urun-fiyat'
      fullPath: '/urun-fiyat'
      preLoaderRoute: typeof AppUrunFiyatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun-fiyat-hesap': {
      id: '/_app/urun-fiyat-hesap'
      path: '/urun-fiyat-hesap'
      fullPath: '/urun-fiyat-hesap'
      preLoaderRoute: typeof AppUrunFiyatHesapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/virman': {
      id: '/_app/virman'
      path: '/virman'
      fullPath: '/virman'
      preLoaderRoute: typeof AppVirmanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/activate': {
      id: '/_app/account/activate'
      path: '/account/activate'
      fullPath: '/account/activate'
      preLoaderRoute: typeof AppAccountActivateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/password': {
      id: '/_app/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AppAccountPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/settings': {
      id: '/_app/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AppAccountSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audits': {
      id: '/_app/admin/audits'
      path: '/admin/audits'
      fullPath: '/admin/audits'
      preLoaderRoute: typeof AppAdminAuditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/health': {
      id: '/_app/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AppAdminHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/operations': {
      id: '/_app/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AppAdminOperationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/user-management': {
      id: '/_app/admin/user-management'
      path: '/admin/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AppAdminUserManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/borc-alacak_/$id': {
      id: '/_app/borc-alacak_/$id'
      path: '/borc-alacak/$id'
      fullPath: '/borc-alacak/$id'
      preLoaderRoute: typeof AppBorcAlacakIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/borc-alacak_/new': {
      id: '/_app/borc-alacak_/new'
      path: '/borc-alacak/new'
      fullPath: '/borc-alacak/new'
      preLoaderRoute: typeof AppBorcAlacakNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gider_/$id': {
      id: '/_app/gider_/$id'
      path: '/gider/$id'
      fullPath: '/gider/$id'
      preLoaderRoute: typeof AppGiderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gider_/new': {
      id: '/_app/gider_/new'
      path: '/gider/new'
      fullPath: '/gider/new'
      preLoaderRoute: typeof AppGiderNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kasa-hareketleri_/$id': {
      id: '/_app/kasa-hareketleri_/$id'
      path: '/kasa-hareketleri/$id'
      fullPath: '/kasa-hareketleri/$id'
      preLoaderRoute: typeof AppKasaHareketleriIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kasa-hareketleri_/new': {
      id: '/_app/kasa-hareketleri_/new'
      path: '/kasa-hareketleri/new'
      fullPath: '/kasa-hareketleri/new'
      preLoaderRoute: typeof AppKasaHareketleriNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kdv-kategorisi_/$id': {
      id: '/_app/kdv-kategorisi_/$id'
      path: '/kdv-kategorisi/$id'
      fullPath: '/kdv-kategorisi/$id'
      preLoaderRoute: typeof AppKdvKategorisiIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kdv-kategorisi_/new': {
      id: '/_app/kdv-kategorisi_/new'
      path: '/kdv-kategorisi/new'
      fullPath: '/kdv-kategorisi/new'
      preLoaderRoute: typeof AppKdvKategorisiNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kisiler_/$id': {
      id: '/_app/kisiler_/$id'
      path: '/kisiler/$id'
      fullPath: '/kisiler/$id'
      preLoaderRoute: typeof AppKisilerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kisiler_/new': {
      id: '/_app/kisiler_/new'
      path: '/kisiler/new'
      fullPath: '/kisiler/new'
      preLoaderRoute: typeof AppKisilerNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nobet-hareketleri_/$id': {
      id: '/_app/nobet-hareketleri_/$id'
      path: '/nobet-hareketleri/$id'
      fullPath: '/nobet-hareketleri/$id'
      preLoaderRoute: typeof AppNobetHareketleriIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nobet-hareketleri_/new': {
      id: '/_app/nobet-hareketleri_/new'
      path: '/nobet-hareketleri/new'
      fullPath: '/nobet-hareketleri/new'
      preLoaderRoute: typeof AppNobetHareketleriNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/aylikSatislar': {
      id: '/_app/reports/aylikSatislar'
      path: '/reports/aylikSatislar'
      fullPath: '/reports/aylikSatislar'
      preLoaderRoute: typeof AppReportsAylikSatislarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/aylikSatislarMali': {
      id: '/_app/reports/aylikSatislarMali'
      path: '/reports/aylikSatislarMali'
      fullPath: '/reports/aylikSatislarMali'
      preLoaderRoute: typeof AppReportsAylikSatislarMaliRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/ciro': {
      id: '/_app/reports/ciro'
      path: '/reports/ciro'
      fullPath: '/reports/ciro'
      preLoaderRoute: typeof AppReportsCiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/ortakFaturalar': {
      id: '/_app/reports/ortakFaturalar'
      path: '/reports/ortakFaturalar'
      fullPath: '/reports/ortakFaturalar'
      preLoaderRoute: typeof AppReportsOrtakFaturalarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/stock': {
      id: '/_app/reports/stock'
      path: '/reports/stock'
      fullPath: '/reports/stock'
      preLoaderRoute: typeof AppReportsStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/tukenme': {
      id: '/_app/reports/tukenme'
      path: '/reports/tukenme'
      fullPath: '/reports/tukenme'
      preLoaderRoute: typeof AppReportsTukenmeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satis-stok-hareketleri_/$id': {
      id: '/_app/satis-stok-hareketleri_/$id'
      path: '/satis-stok-hareketleri/$id'
      fullPath: '/satis-stok-hareketleri/$id'
      preLoaderRoute: typeof AppSatisStokHareketleriIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satis-stok-hareketleri_/new': {
      id: '/_app/satis-stok-hareketleri_/new'
      path: '/satis-stok-hareketleri/new'
      fullPath: '/satis-stok-hareketleri/new'
      preLoaderRoute: typeof AppSatisStokHareketleriNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satis_/$id': {
      id: '/_app/satis_/$id'
      path: '/satis/$id'
      fullPath: '/satis/$id'
      preLoaderRoute: typeof AppSatisIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satis_/new': {
      id: '/_app/satis_/new'
      path: '/satis/new'
      fullPath: '/satis/new'
      preLoaderRoute: typeof AppSatisNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stok-girisi_/$id': {
      id: '/_app/stok-girisi_/$id'
      path: '/stok-girisi/$id'
      fullPath: '/stok-girisi/$id'
      preLoaderRoute: typeof AppStokGirisiIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stok-girisi_/new': {
      id: '/_app/stok-girisi_/new'
      path: '/stok-girisi/new'
      fullPath: '/stok-girisi/new'
      preLoaderRoute: typeof AppStokGirisiNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uretici-odemeleri_/$id': {
      id: '/_app/uretici-odemeleri_/$id'
      path: '/uretici-odemeleri/$id'
      fullPath: '/uretici-odemeleri/$id'
      preLoaderRoute: typeof AppUreticiOdemeleriIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uretici-odemeleri_/new': {
      id: '/_app/uretici-odemeleri_/new'
      path: '/uretici-odemeleri/new'
      fullPath: '/uretici-odemeleri/new'
      preLoaderRoute: typeof AppUreticiOdemeleriNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uretici_/$id': {
      id: '/_app/uretici_/$id'
      path: '/uretici/$id'
      fullPath: '/uretici/$id'
      preLoaderRoute: typeof AppUreticiIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uretici_/new': {
      id: '/_app/uretici_/new'
      path: '/uretici/new'
      fullPath: '/uretici/new'
      preLoaderRoute: typeof AppUreticiNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun-fiyat-hesap_/$id': {
      id: '/_app/urun-fiyat-hesap_/$id'
      path: '/urun-fiyat-hesap/$id'
      fullPath: '/urun-fiyat-hesap/$id'
      preLoaderRoute: typeof AppUrunFiyatHesapIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun-fiyat-hesap_/new': {
      id: '/_app/urun-fiyat-hesap_/new'
      path: '/urun-fiyat-hesap/new'
      fullPath: '/urun-fiyat-hesap/new'
      preLoaderRoute: typeof AppUrunFiyatHesapNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun-fiyat_/$id': {
      id: '/_app/urun-fiyat_/$id'
      path: '/urun-fiyat/$id'
      fullPath: '/urun-fiyat/$id'
      preLoaderRoute: typeof AppUrunFiyatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun-fiyat_/new': {
      id: '/_app/urun-fiyat_/new'
      path: '/urun-fiyat/new'
      fullPath: '/urun-fiyat/new'
      preLoaderRoute: typeof AppUrunFiyatNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun_/$id': {
      id: '/_app/urun_/$id'
      path: '/urun/$id'
      fullPath: '/urun/$id'
      preLoaderRoute: typeof AppUrunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun_/new': {
      id: '/_app/urun_/new'
      path: '/urun/new'
      fullPath: '/urun/new'
      preLoaderRoute: typeof AppUrunNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/virman_/$id': {
      id: '/_app/virman_/$id'
      path: '/virman/$id'
      fullPath: '/virman/$id'
      preLoaderRoute: typeof AppVirmanIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/virman_/new': {
      id: '/_app/virman_/new'
      path: '/virman/new'
      fullPath: '/virman/new'
      preLoaderRoute: typeof AppVirmanNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/reset/finish': {
      id: '/_app/account/reset/finish'
      path: '/account/reset/finish'
      fullPath: '/account/reset/finish'
      preLoaderRoute: typeof AppAccountResetFinishRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/reset/request': {
      id: '/_app/account/reset/request'
      path: '/account/reset/request'
      fullPath: '/account/reset/request'
      preLoaderRoute: typeof AppAccountResetRequestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/user-management_/$login': {
      id: '/_app/admin/user-management_/$login'
      path: '/admin/user-management/$login'
      fullPath: '/admin/user-management/$login'
      preLoaderRoute: typeof AppAdminUserManagementLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/user-management_/new': {
      id: '/_app/admin/user-management_/new'
      path: '/admin/user-management/new'
      fullPath: '/admin/user-management/new'
      preLoaderRoute: typeof AppAdminUserManagementNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/borc-alacak_/$id_/delete': {
      id: '/_app/borc-alacak_/$id_/delete'
      path: '/borc-alacak/$id/delete'
      fullPath: '/borc-alacak/$id/delete'
      preLoaderRoute: typeof AppBorcAlacakIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/borc-alacak_/$id_/edit': {
      id: '/_app/borc-alacak_/$id_/edit'
      path: '/borc-alacak/$id/edit'
      fullPath: '/borc-alacak/$id/edit'
      preLoaderRoute: typeof AppBorcAlacakIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gider_/$id_/delete': {
      id: '/_app/gider_/$id_/delete'
      path: '/gider/$id/delete'
      fullPath: '/gider/$id/delete'
      preLoaderRoute: typeof AppGiderIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gider_/$id_/edit': {
      id: '/_app/gider_/$id_/edit'
      path: '/gider/$id/edit'
      fullPath: '/gider/$id/edit'
      preLoaderRoute: typeof AppGiderIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kasa-hareketleri_/$id_/delete': {
      id: '/_app/kasa-hareketleri_/$id_/delete'
      path: '/kasa-hareketleri/$id/delete'
      fullPath: '/kasa-hareketleri/$id/delete'
      preLoaderRoute: typeof AppKasaHareketleriIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kasa-hareketleri_/$id_/edit': {
      id: '/_app/kasa-hareketleri_/$id_/edit'
      path: '/kasa-hareketleri/$id/edit'
      fullPath: '/kasa-hareketleri/$id/edit'
      preLoaderRoute: typeof AppKasaHareketleriIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kdv-kategorisi_/$id_/delete': {
      id: '/_app/kdv-kategorisi_/$id_/delete'
      path: '/kdv-kategorisi/$id/delete'
      fullPath: '/kdv-kategorisi/$id/delete'
      preLoaderRoute: typeof AppKdvKategorisiIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kdv-kategorisi_/$id_/edit': {
      id: '/_app/kdv-kategorisi_/$id_/edit'
      path: '/kdv-kategorisi/$id/edit'
      fullPath: '/kdv-kategorisi/$id/edit'
      preLoaderRoute: typeof AppKdvKategorisiIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kisiler_/$id_/delete': {
      id: '/_app/kisiler_/$id_/delete'
      path: '/kisiler/$id/delete'
      fullPath: '/kisiler/$id/delete'
      preLoaderRoute: typeof AppKisilerIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kisiler_/$id_/edit': {
      id: '/_app/kisiler_/$id_/edit'
      path: '/kisiler/$id/edit'
      fullPath: '/kisiler/$id/edit'
      preLoaderRoute: typeof AppKisilerIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nobet-hareketleri_/$id_/delete': {
      id: '/_app/nobet-hareketleri_/$id_/delete'
      path: '/nobet-hareketleri/$id/delete'
      fullPath: '/nobet-hareketleri/$id/delete'
      preLoaderRoute: typeof AppNobetHareketleriIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nobet-hareketleri_/$id_/edit': {
      id: '/_app/nobet-hareketleri_/$id_/edit'
      path: '/nobet-hareketleri/$id/edit'
      fullPath: '/nobet-hareketleri/$id/edit'
      preLoaderRoute: typeof AppNobetHareketleriIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/ciro_/$id': {
      id: '/_app/reports/ciro_/$id'
      path: '/reports/ciro/$id'
      fullPath: '/reports/ciro/$id'
      preLoaderRoute: typeof AppReportsCiroIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/ortakFaturalar_/$id': {
      id: '/_app/reports/ortakFaturalar_/$id'
      path: '/reports/ortakFaturalar/$id'
      fullPath: '/reports/ortakFaturalar/$id'
      preLoaderRoute: typeof AppReportsOrtakFaturalarIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satis-stok-hareketleri_/$id_/delete': {
      id: '/_app/satis-stok-hareketleri_/$id_/delete'
      path: '/satis-stok-hareketleri/$id/delete'
      fullPath: '/satis-stok-hareketleri/$id/delete'
      preLoaderRoute: typeof AppSatisStokHareketleriIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satis-stok-hareketleri_/$id_/edit': {
      id: '/_app/satis-stok-hareketleri_/$id_/edit'
      path: '/satis-stok-hareketleri/$id/edit'
      fullPath: '/satis-stok-hareketleri/$id/edit'
      preLoaderRoute: typeof AppSatisStokHareketleriIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satis_/$id_/delete': {
      id: '/_app/satis_/$id_/delete'
      path: '/satis/$id/delete'
      fullPath: '/satis/$id/delete'
      preLoaderRoute: typeof AppSatisIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satis_/$id_/edit': {
      id: '/_app/satis_/$id_/edit'
      path: '/satis/$id/edit'
      fullPath: '/satis/$id/edit'
      preLoaderRoute: typeof AppSatisIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stok-girisi_/$id_/delete': {
      id: '/_app/stok-girisi_/$id_/delete'
      path: '/stok-girisi/$id/delete'
      fullPath: '/stok-girisi/$id/delete'
      preLoaderRoute: typeof AppStokGirisiIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stok-girisi_/$id_/edit': {
      id: '/_app/stok-girisi_/$id_/edit'
      path: '/stok-girisi/$id/edit'
      fullPath: '/stok-girisi/$id/edit'
      preLoaderRoute: typeof AppStokGirisiIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uretici-odemeleri_/$id_/delete': {
      id: '/_app/uretici-odemeleri_/$id_/delete'
      path: '/uretici-odemeleri/$id/delete'
      fullPath: '/uretici-odemeleri/$id/delete'
      preLoaderRoute: typeof AppUreticiOdemeleriIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uretici-odemeleri_/$id_/edit': {
      id: '/_app/uretici-odemeleri_/$id_/edit'
      path: '/uretici-odemeleri/$id/edit'
      fullPath: '/uretici-odemeleri/$id/edit'
      preLoaderRoute: typeof AppUreticiOdemeleriIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uretici_/$id_/delete': {
      id: '/_app/uretici_/$id_/delete'
      path: '/uretici/$id/delete'
      fullPath: '/uretici/$id/delete'
      preLoaderRoute: typeof AppUreticiIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uretici_/$id_/edit': {
      id: '/_app/uretici_/$id_/edit'
      path: '/uretici/$id/edit'
      fullPath: '/uretici/$id/edit'
      preLoaderRoute: typeof AppUreticiIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun-fiyat-hesap_/$id_/delete': {
      id: '/_app/urun-fiyat-hesap_/$id_/delete'
      path: '/urun-fiyat-hesap/$id/delete'
      fullPath: '/urun-fiyat-hesap/$id/delete'
      preLoaderRoute: typeof AppUrunFiyatHesapIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun-fiyat-hesap_/$id_/edit': {
      id: '/_app/urun-fiyat-hesap_/$id_/edit'
      path: '/urun-fiyat-hesap/$id/edit'
      fullPath: '/urun-fiyat-hesap/$id/edit'
      preLoaderRoute: typeof AppUrunFiyatHesapIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun-fiyat_/$id_/delete': {
      id: '/_app/urun-fiyat_/$id_/delete'
      path: '/urun-fiyat/$id/delete'
      fullPath: '/urun-fiyat/$id/delete'
      preLoaderRoute: typeof AppUrunFiyatIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun-fiyat_/$id_/edit': {
      id: '/_app/urun-fiyat_/$id_/edit'
      path: '/urun-fiyat/$id/edit'
      fullPath: '/urun-fiyat/$id/edit'
      preLoaderRoute: typeof AppUrunFiyatIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun_/$id_/delete': {
      id: '/_app/urun_/$id_/delete'
      path: '/urun/$id/delete'
      fullPath: '/urun/$id/delete'
      preLoaderRoute: typeof AppUrunIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urun_/$id_/edit': {
      id: '/_app/urun_/$id_/edit'
      path: '/urun/$id/edit'
      fullPath: '/urun/$id/edit'
      preLoaderRoute: typeof AppUrunIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/virman_/$id_/delete': {
      id: '/_app/virman_/$id_/delete'
      path: '/virman/$id/delete'
      fullPath: '/virman/$id/delete'
      preLoaderRoute: typeof AppVirmanIdDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/virman_/$id_/edit': {
      id: '/_app/virman_/$id_/edit'
      path: '/virman/$id/edit'
      fullPath: '/virman/$id/edit'
      preLoaderRoute: typeof AppVirmanIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/user-management_/$login_/delete': {
      id: '/_app/admin/user-management_/$login_/delete'
      path: '/admin/user-management/$login/delete'
      fullPath: '/admin/user-management/$login/delete'
      preLoaderRoute: typeof AppAdminUserManagementLoginDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/user-management_/$login_/edit': {
      id: '/_app/admin/user-management_/$login_/edit'
      path: '/admin/user-management/$login/edit'
      fullPath: '/admin/user-management/$login/edit'
      preLoaderRoute: typeof AppAdminUserManagementLoginEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppBorcAlacakRoute: typeof AppBorcAlacakRoute
  AppGiderRoute: typeof AppGiderRoute
  AppKasaHareketleriRoute: typeof AppKasaHareketleriRoute
  AppKdvKategorisiRoute: typeof AppKdvKategorisiRoute
  AppKisilerRoute: typeof AppKisilerRoute
  AppLoginRoute: typeof AppLoginRoute
  AppLogoutRoute: typeof AppLogoutRoute
  AppNobetHareketleriRoute: typeof AppNobetHareketleriRoute
  AppSatisRoute: typeof AppSatisRoute
  AppSatisStokHareketleriRoute: typeof AppSatisStokHareketleriRoute
  AppStokGirisiRoute: typeof AppStokGirisiRoute
  AppUreticiRoute: typeof AppUreticiRoute
  AppUreticiOdemeleriRoute: typeof AppUreticiOdemeleriRoute
  AppUrunRoute: typeof AppUrunRoute
  AppUrunFiyatRoute: typeof AppUrunFiyatRoute
  AppUrunFiyatHesapRoute: typeof AppUrunFiyatHesapRoute
  AppVirmanRoute: typeof AppVirmanRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountActivateRoute: typeof AppAccountActivateRoute
  AppAccountPasswordRoute: typeof AppAccountPasswordRoute
  AppAccountSettingsRoute: typeof AppAccountSettingsRoute
  AppAdminAuditsRoute: typeof AppAdminAuditsRoute
  AppAdminHealthRoute: typeof AppAdminHealthRoute
  AppAdminOperationsRoute: typeof AppAdminOperationsRoute
  AppAdminUserManagementRoute: typeof AppAdminUserManagementRoute
  AppBorcAlacakIdRoute: typeof AppBorcAlacakIdRoute
  AppBorcAlacakNewRoute: typeof AppBorcAlacakNewRoute
  AppGiderIdRoute: typeof AppGiderIdRoute
  AppGiderNewRoute: typeof AppGiderNewRoute
  AppKasaHareketleriIdRoute: typeof AppKasaHareketleriIdRoute
  AppKasaHareketleriNewRoute: typeof AppKasaHareketleriNewRoute
  AppKdvKategorisiIdRoute: typeof AppKdvKategorisiIdRoute
  AppKdvKategorisiNewRoute: typeof AppKdvKategorisiNewRoute
  AppKisilerIdRoute: typeof AppKisilerIdRoute
  AppKisilerNewRoute: typeof AppKisilerNewRoute
  AppNobetHareketleriIdRoute: typeof AppNobetHareketleriIdRoute
  AppNobetHareketleriNewRoute: typeof AppNobetHareketleriNewRoute
  AppReportsAylikSatislarRoute: typeof AppReportsAylikSatislarRoute
  AppReportsAylikSatislarMaliRoute: typeof AppReportsAylikSatislarMaliRoute
  AppReportsCiroRoute: typeof AppReportsCiroRoute
  AppReportsOrtakFaturalarRoute: typeof AppReportsOrtakFaturalarRoute
  AppReportsStockRoute: typeof AppReportsStockRoute
  AppReportsTukenmeRoute: typeof AppReportsTukenmeRoute
  AppSatisStokHareketleriIdRoute: typeof AppSatisStokHareketleriIdRoute
  AppSatisStokHareketleriNewRoute: typeof AppSatisStokHareketleriNewRoute
  AppSatisIdRoute: typeof AppSatisIdRoute
  AppSatisNewRoute: typeof AppSatisNewRoute
  AppStokGirisiIdRoute: typeof AppStokGirisiIdRoute
  AppStokGirisiNewRoute: typeof AppStokGirisiNewRoute
  AppUreticiOdemeleriIdRoute: typeof AppUreticiOdemeleriIdRoute
  AppUreticiOdemeleriNewRoute: typeof AppUreticiOdemeleriNewRoute
  AppUreticiIdRoute: typeof AppUreticiIdRoute
  AppUreticiNewRoute: typeof AppUreticiNewRoute
  AppUrunFiyatHesapIdRoute: typeof AppUrunFiyatHesapIdRoute
  AppUrunFiyatHesapNewRoute: typeof AppUrunFiyatHesapNewRoute
  AppUrunFiyatIdRoute: typeof AppUrunFiyatIdRoute
  AppUrunFiyatNewRoute: typeof AppUrunFiyatNewRoute
  AppUrunIdRoute: typeof AppUrunIdRoute
  AppUrunNewRoute: typeof AppUrunNewRoute
  AppVirmanIdRoute: typeof AppVirmanIdRoute
  AppVirmanNewRoute: typeof AppVirmanNewRoute
  AppAccountResetFinishRoute: typeof AppAccountResetFinishRoute
  AppAccountResetRequestRoute: typeof AppAccountResetRequestRoute
  AppAdminUserManagementLoginRoute: typeof AppAdminUserManagementLoginRoute
  AppAdminUserManagementNewRoute: typeof AppAdminUserManagementNewRoute
  AppBorcAlacakIdDeleteRoute: typeof AppBorcAlacakIdDeleteRoute
  AppBorcAlacakIdEditRoute: typeof AppBorcAlacakIdEditRoute
  AppGiderIdDeleteRoute: typeof AppGiderIdDeleteRoute
  AppGiderIdEditRoute: typeof AppGiderIdEditRoute
  AppKasaHareketleriIdDeleteRoute: typeof AppKasaHareketleriIdDeleteRoute
  AppKasaHareketleriIdEditRoute: typeof AppKasaHareketleriIdEditRoute
  AppKdvKategorisiIdDeleteRoute: typeof AppKdvKategorisiIdDeleteRoute
  AppKdvKategorisiIdEditRoute: typeof AppKdvKategorisiIdEditRoute
  AppKisilerIdDeleteRoute: typeof AppKisilerIdDeleteRoute
  AppKisilerIdEditRoute: typeof AppKisilerIdEditRoute
  AppNobetHareketleriIdDeleteRoute: typeof AppNobetHareketleriIdDeleteRoute
  AppNobetHareketleriIdEditRoute: typeof AppNobetHareketleriIdEditRoute
  AppReportsCiroIdRoute: typeof AppReportsCiroIdRoute
  AppReportsOrtakFaturalarIdRoute: typeof AppReportsOrtakFaturalarIdRoute
  AppSatisStokHareketleriIdDeleteRoute: typeof AppSatisStokHareketleriIdDeleteRoute
  AppSatisStokHareketleriIdEditRoute: typeof AppSatisStokHareketleriIdEditRoute
  AppSatisIdDeleteRoute: typeof AppSatisIdDeleteRoute
  AppSatisIdEditRoute: typeof AppSatisIdEditRoute
  AppStokGirisiIdDeleteRoute: typeof AppStokGirisiIdDeleteRoute
  AppStokGirisiIdEditRoute: typeof AppStokGirisiIdEditRoute
  AppUreticiOdemeleriIdDeleteRoute: typeof AppUreticiOdemeleriIdDeleteRoute
  AppUreticiOdemeleriIdEditRoute: typeof AppUreticiOdemeleriIdEditRoute
  AppUreticiIdDeleteRoute: typeof AppUreticiIdDeleteRoute
  AppUreticiIdEditRoute: typeof AppUreticiIdEditRoute
  AppUrunFiyatHesapIdDeleteRoute: typeof AppUrunFiyatHesapIdDeleteRoute
  AppUrunFiyatHesapIdEditRoute: typeof AppUrunFiyatHesapIdEditRoute
  AppUrunFiyatIdDeleteRoute: typeof AppUrunFiyatIdDeleteRoute
  AppUrunFiyatIdEditRoute: typeof AppUrunFiyatIdEditRoute
  AppUrunIdDeleteRoute: typeof AppUrunIdDeleteRoute
  AppUrunIdEditRoute: typeof AppUrunIdEditRoute
  AppVirmanIdDeleteRoute: typeof AppVirmanIdDeleteRoute
  AppVirmanIdEditRoute: typeof AppVirmanIdEditRoute
  AppAdminUserManagementLoginDeleteRoute: typeof AppAdminUserManagementLoginDeleteRoute
  AppAdminUserManagementLoginEditRoute: typeof AppAdminUserManagementLoginEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppBorcAlacakRoute: AppBorcAlacakRoute,
  AppGiderRoute: AppGiderRoute,
  AppKasaHareketleriRoute: AppKasaHareketleriRoute,
  AppKdvKategorisiRoute: AppKdvKategorisiRoute,
  AppKisilerRoute: AppKisilerRoute,
  AppLoginRoute: AppLoginRoute,
  AppLogoutRoute: AppLogoutRoute,
  AppNobetHareketleriRoute: AppNobetHareketleriRoute,
  AppSatisRoute: AppSatisRoute,
  AppSatisStokHareketleriRoute: AppSatisStokHareketleriRoute,
  AppStokGirisiRoute: AppStokGirisiRoute,
  AppUreticiRoute: AppUreticiRoute,
  AppUreticiOdemeleriRoute: AppUreticiOdemeleriRoute,
  AppUrunRoute: AppUrunRoute,
  AppUrunFiyatRoute: AppUrunFiyatRoute,
  AppUrunFiyatHesapRoute: AppUrunFiyatHesapRoute,
  AppVirmanRoute: AppVirmanRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountActivateRoute: AppAccountActivateRoute,
  AppAccountPasswordRoute: AppAccountPasswordRoute,
  AppAccountSettingsRoute: AppAccountSettingsRoute,
  AppAdminAuditsRoute: AppAdminAuditsRoute,
  AppAdminHealthRoute: AppAdminHealthRoute,
  AppAdminOperationsRoute: AppAdminOperationsRoute,
  AppAdminUserManagementRoute: AppAdminUserManagementRoute,
  AppBorcAlacakIdRoute: AppBorcAlacakIdRoute,
  AppBorcAlacakNewRoute: AppBorcAlacakNewRoute,
  AppGiderIdRoute: AppGiderIdRoute,
  AppGiderNewRoute: AppGiderNewRoute,
  AppKasaHareketleriIdRoute: AppKasaHareketleriIdRoute,
  AppKasaHareketleriNewRoute: AppKasaHareketleriNewRoute,
  AppKdvKategorisiIdRoute: AppKdvKategorisiIdRoute,
  AppKdvKategorisiNewRoute: AppKdvKategorisiNewRoute,
  AppKisilerIdRoute: AppKisilerIdRoute,
  AppKisilerNewRoute: AppKisilerNewRoute,
  AppNobetHareketleriIdRoute: AppNobetHareketleriIdRoute,
  AppNobetHareketleriNewRoute: AppNobetHareketleriNewRoute,
  AppReportsAylikSatislarRoute: AppReportsAylikSatislarRoute,
  AppReportsAylikSatislarMaliRoute: AppReportsAylikSatislarMaliRoute,
  AppReportsCiroRoute: AppReportsCiroRoute,
  AppReportsOrtakFaturalarRoute: AppReportsOrtakFaturalarRoute,
  AppReportsStockRoute: AppReportsStockRoute,
  AppReportsTukenmeRoute: AppReportsTukenmeRoute,
  AppSatisStokHareketleriIdRoute: AppSatisStokHareketleriIdRoute,
  AppSatisStokHareketleriNewRoute: AppSatisStokHareketleriNewRoute,
  AppSatisIdRoute: AppSatisIdRoute,
  AppSatisNewRoute: AppSatisNewRoute,
  AppStokGirisiIdRoute: AppStokGirisiIdRoute,
  AppStokGirisiNewRoute: AppStokGirisiNewRoute,
  AppUreticiOdemeleriIdRoute: AppUreticiOdemeleriIdRoute,
  AppUreticiOdemeleriNewRoute: AppUreticiOdemeleriNewRoute,
  AppUreticiIdRoute: AppUreticiIdRoute,
  AppUreticiNewRoute: AppUreticiNewRoute,
  AppUrunFiyatHesapIdRoute: AppUrunFiyatHesapIdRoute,
  AppUrunFiyatHesapNewRoute: AppUrunFiyatHesapNewRoute,
  AppUrunFiyatIdRoute: AppUrunFiyatIdRoute,
  AppUrunFiyatNewRoute: AppUrunFiyatNewRoute,
  AppUrunIdRoute: AppUrunIdRoute,
  AppUrunNewRoute: AppUrunNewRoute,
  AppVirmanIdRoute: AppVirmanIdRoute,
  AppVirmanNewRoute: AppVirmanNewRoute,
  AppAccountResetFinishRoute: AppAccountResetFinishRoute,
  AppAccountResetRequestRoute: AppAccountResetRequestRoute,
  AppAdminUserManagementLoginRoute: AppAdminUserManagementLoginRoute,
  AppAdminUserManagementNewRoute: AppAdminUserManagementNewRoute,
  AppBorcAlacakIdDeleteRoute: AppBorcAlacakIdDeleteRoute,
  AppBorcAlacakIdEditRoute: AppBorcAlacakIdEditRoute,
  AppGiderIdDeleteRoute: AppGiderIdDeleteRoute,
  AppGiderIdEditRoute: AppGiderIdEditRoute,
  AppKasaHareketleriIdDeleteRoute: AppKasaHareketleriIdDeleteRoute,
  AppKasaHareketleriIdEditRoute: AppKasaHareketleriIdEditRoute,
  AppKdvKategorisiIdDeleteRoute: AppKdvKategorisiIdDeleteRoute,
  AppKdvKategorisiIdEditRoute: AppKdvKategorisiIdEditRoute,
  AppKisilerIdDeleteRoute: AppKisilerIdDeleteRoute,
  AppKisilerIdEditRoute: AppKisilerIdEditRoute,
  AppNobetHareketleriIdDeleteRoute: AppNobetHareketleriIdDeleteRoute,
  AppNobetHareketleriIdEditRoute: AppNobetHareketleriIdEditRoute,
  AppReportsCiroIdRoute: AppReportsCiroIdRoute,
  AppReportsOrtakFaturalarIdRoute: AppReportsOrtakFaturalarIdRoute,
  AppSatisStokHareketleriIdDeleteRoute: AppSatisStokHareketleriIdDeleteRoute,
  AppSatisStokHareketleriIdEditRoute: AppSatisStokHareketleriIdEditRoute,
  AppSatisIdDeleteRoute: AppSatisIdDeleteRoute,
  AppSatisIdEditRoute: AppSatisIdEditRoute,
  AppStokGirisiIdDeleteRoute: AppStokGirisiIdDeleteRoute,
  AppStokGirisiIdEditRoute: AppStokGirisiIdEditRoute,
  AppUreticiOdemeleriIdDeleteRoute: AppUreticiOdemeleriIdDeleteRoute,
  AppUreticiOdemeleriIdEditRoute: AppUreticiOdemeleriIdEditRoute,
  AppUreticiIdDeleteRoute: AppUreticiIdDeleteRoute,
  AppUreticiIdEditRoute: AppUreticiIdEditRoute,
  AppUrunFiyatHesapIdDeleteRoute: AppUrunFiyatHesapIdDeleteRoute,
  AppUrunFiyatHesapIdEditRoute: AppUrunFiyatHesapIdEditRoute,
  AppUrunFiyatIdDeleteRoute: AppUrunFiyatIdDeleteRoute,
  AppUrunFiyatIdEditRoute: AppUrunFiyatIdEditRoute,
  AppUrunIdDeleteRoute: AppUrunIdDeleteRoute,
  AppUrunIdEditRoute: AppUrunIdEditRoute,
  AppVirmanIdDeleteRoute: AppVirmanIdDeleteRoute,
  AppVirmanIdEditRoute: AppVirmanIdEditRoute,
  AppAdminUserManagementLoginDeleteRoute:
    AppAdminUserManagementLoginDeleteRoute,
  AppAdminUserManagementLoginEditRoute: AppAdminUserManagementLoginEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
